import enLocale from 'element-ui/lib/locale/lang/en'
import business_en_Us from '@/views/business/i18n/en_US'

const en_US = {
    routerName:{
        changePassword:'Change Password',
        addUserRemindTepMage:'Add template',
        editUserRemindTepMage:'Modify template',
        addOrganization:'Add Organizatio',
        detailOrganization:'Organization query',
        editOrganization:'Organizational Edit',
        addRoleManagement:'Add Role/ Role Edit',
        lookUser:'View User',
        editRoleManagement:'Role Edit',
        detailRoleManagement:'Role Search',
        addPostManagement:'Add Post ',
        editPostManagement:'Post Edit',
        detailPostManagement:'View Post',
        dictManagement:'Dictionary Management',
        addDictManagement:'Add Dictionary',
        detailDictManagement:'View Dictionary',
        resourcesAdd:'Add resources',
        resourcesEdit:'Resources Edit',
        addRoleAssignment:'Role assignment',
        addForm:'Add Form',
        testFirst:'Test Form',
        addEntrustProcess:'Process delegation',
        entrustProcessView:'View Process delegation',
        modelEdit:'Model Edit',
        formCnfAdd:'Add Form',
        formCnfEdit:'Edit Form',
        editDocument:'Add Information',
        viewDocument:'View Information',
        newsView:'View News',
        newsList:'News List',
        cfieldsView:'Extended field view',
        cfieldsEdit:'Extended field editing',
        imagesEdit:'Add Images',
        imagesView:'View Images',
        custRuleEdit:'Process Rule Editing',
        messageList:'Message List',
        scheduleEdit:'Timing Task Editor',
        scheduleView:'Timing Task View',
        scheduleLogList:'Timing Task Log View',
        operateLogList:'User Operations Log',
        loginLogList:'User Access Log',
        fnPermission:'Function authority',
        dataPermission:'Data permissions',
        branchManagerAdd:'branch Manager Add',
        editDept: 'Dept Editing'
    },
    validate:{
        nextNodeTip:'Next Node can\'t be null',
        dealingPeopleTip:'Dealing People can\'t be null',
        approvalActTip:'Approval Act can\'t be null',
        approvalOpinionTip:'Approval Opinion can\'t be null',
        postCodeTip:'Post Code can\'t be null',
        postNameTip:'Post Name can\'t be null',
        orderNumTip:'Order Num can\'t be null',
        englishNameTip:'Please enter the English name of the module',
        chineseNameTip:'Please enter the Chinese name of the module',
        templateTypeTip:'Please enter the module type',
        documentTypeTip:'Please select the document type',
        documentTitleTip:'Please fill in the title',
        documentEnableTip:'Please choose whether to take effect or not',
        cfObjCodeTip:'Extended object can\'t be null',
        cfCfieldTypeTip:'Field type can\'t be null',
        cfCfieldLabelTip:'Field display name can\'t be null',
        cfCfieldColumnTip:'Database field can\'t be null',
        dataDicTip:'The corresponding data dictionary  can\'t be null',
        nameTip:'Name can\'t be null',
        picTip:'Picture type can\'t be null',
        beanNameTip:'bean Name can\'t be null',
        methodNameTip:'Method Name can\'t be null',
        cronExpressionTip:'Cron Expression can\'t be null',
        modelKeyTip:'Model Key can\'t be null',
        modelKeyUnique:'Model key repetition',
        modelNameTip:'Model Name can\'t be null',
        procNameTip:'Process name can\'t be null',
        procVersionTip:'Version can\'t be null',
        woTypeTip:'Document type can\'t be null',
        urlTip:'Jump path can\'t be null',
        orderTypeTip:'Order Type can\'t be null',
        processNameTip:'Process Name can\'t be null',
        processKeyTip:'Process Key can\'t be null',
        nodeCodeTip:'Node Code can\'t be null',
        pwdCurTip:'The Old password can\'t be null',
        pwdNewTip:'The New password can\'t be null',
        pwdConfirmTip:'The Confirm password can\'t be null',
        TransferredPersonTip:'Transferred Person can\'t be null',
        TransactorsTip:'Transactors can\'t be null'
    },
    errorMsg:{
        abnormalDocuments:'Document exceptions, not operational, please refresh the document or contact the administrator.',
        processException:'Process exception, please contact administrator',
        concurrentFlow:'Concurrent Flow Not All Choices!',
        manMadeEmpty:'Man-made empty processing, please choose the handler!',
        noDirection:'No choice of direction, please choose!',
        havePostCode:'Job code already exists! Please re-enter the post code!',
        comCharList:'Please enter a complete character list',
        repeatCharList:'Character list is not repeatable',
        haveEnglishTem:'The English name of the template already exists! Please re-enter the English name of the template!',
        haveChineseTem:'The Chinese name of the template already exists! Please re-enter the Chinese name of the template!'

    },
    placeHolder:{
        date:'Please choose the date',
        input:'Please input',
        select:'Please select'
    },
    waring:{
        del:'Whether to permanently delete this data？'
    },
    common:{
        search:'Search',
        reset:'Reset',
        add:'Add',
        view:'View',
        edit:'Edit',
        delete:'Delete',
        order:'Order',
        save:'Save',
        back:'Back',
        action:'Act',
        confirm:'Confirm',
        cancel:'Cancel',
        home:'Home',
        logout:'Logout',
        changePass:'Change Password',
        logoutWeb:'Logout',
        pleaseSelect:'Please Select',
        pleaseChooseData:'Please Choose Data',
        choose:'Opt',
        unselected:'Please select one',
        delConfirm:'Are you sure to delete this data?',
        prompt:'Prompt',
        delSuccess:'Delete successful',
        unDelete:'Cannot delete',
        saveSuccess:'Saved Successfully',
        saveFail:'Saved Failed',
        dataCheckFailed:'Data check failed',
        searchTerm:'Please enter a search term',
        noResult:'No search results',
        result:'Search results',
        internaInfo:'Interna Info',
        processTrace:'Process Trace',
        currentName:'Cur Node',
        confirmClosing:'Confirm closing ?',
        setUpSuccessfully:'Set up successfully',
        status:'Status',
        addRow:'Add Row',
        delRow:'Del Row',
        enterComplete:'Please enter the complete content',
        editBox:'Edit box',
        enable:'enable',
        unable:'unable',
        uploadFail:'Upload Fail',
        pause:'Pause',
        recover:'Recover',
        pauseSuccess:'Pause Success',
        pauseFail:'Pause Fail',
        recoverSuccess:'Recover Success',
        recoverFail:'Recover Fail',
        hideSideBars:'Hide sidebars',
        hideHeader:'Hide Header',
        yes:'yes',
        no:'no',
        leftMenu:'Top Menu'
    },
    loginPage: {
        loginWelcome:'Welcome Login',
        loginTit: 'Login',
        placeholderName:'',
        placeholderPass:'',
        loginAccontTip:'username can\'t be null',
        loginPassTip:'password can\'t be null',
        forgetPwd:'Forget the password'
    },
    homePage:{
        newsImg:'News Image',
        newsAd:'News',
        usualMenu:'Common Menu',
        itemNews:'Project News',
        fastLink:'Fast Link',
        todoWork:'Todo Work',
        todayWork:'Today remainder work',
        todo:'To Do',
        did:'Done',
        toRead:'To Read',
        readed:'Readed',
        labelSelect:'Label Select',
        closeAll:'Close All',
        closeOther:'Close Other',
        showHead:'Show Header'
    },
    userPage:{
        viewUser:'View User',
        editUser:'Added/Edited Users',
        orgStructs:'Org Structure',
        userManage:'User Manage',
        userInfo:'User Info',
        enable:'Enable',
        unable:'Unable',
        sex:'Sex',
        dateOfBirth:'Date of birth',
        enableSuccess:'Enable Successfully',
        unableSuccess:'Unable Successfully',
        loginName:'Login Name',
        name:'Name',
        userCode:'User Code',
        userType:'User Type',
        inside:'Inside',
        director:'Director',
        position:'Position',
        outside:'Outside',
        department:'Department',
        mobile:'Mobile',
        fixedTelephone:'Fixed telephone',
        email:'Email',
        role:'Role',
        userStatus:'Status',
        male:'Male',
        female:'Female',
        roleName:'Role Name',
        roleCode:'Role Code',
        company:'The Company',
        resetPassword:'Password mandatory expiration',
        userExtensionInfo:'User Extension Information',
        userRoleInfo:'User role information',
        generalUser:'General user',
        deleteMessage:'This user has been enabled in other locations and cannot be deleted!',
        userNameRepeat:'The login name is duplicated. Please modify i',
        userCodeRepeat:'User code duplicate, please modify',
        enterNum:'Please enter a numeric value',
        resetPasswordSuccess:'Password Reset Successful!',
        errorMsg:{
            mobile:'Incorrect format of mobile phone number',
            mail:'Please enter the correct mailbox format',
            fixedTelephone:'Fixed phone number format incorrect'
        },
        placeholder:{
            company:'please choose company',
            loginName: 'please input login name',
            name:'please input name',
            userStatus: 'please choose status',
            deparment:'Please enter your department',
            fixedTelephone:'Please fill in the landline',
            userType:'Please select user type',
            userCode:'Please enter user code',
            length:'Length 1 to 250 characters',
            sex:'Please choose gender',
            birthday:'Please enter the date of birth',
            position:'Please enter the position'
        }
    },
    orgPage:{
        orgExtensionInfo:'Organizational Extension Information',
        tenantName:'company',
        orgManage:'Org Manage',
        orgCode:'Org Code',
        orgName:'Org Name',
        upperOrg:'Parent Org',
        orgShort:'Org Shorter',
        orgStatus:'Status',
        orgType:'Org Type',
        enable:'enable',
        unable:'unable',
        placeholder:{
            orgCode:'',
            orgName:'',
            tenantName:'Please choose the company',
            upperOrg:'',
            orgType:'',
            orgShort:'',
        },
        displayMode: 'Display mode',
        list: 'List',
        level: 'Level',
        repeatOrgCode: 'The company code already exists'
    },
    deptPage: {
        deptExtensionInfo: 'Dept Extension Information',
        deptManage: 'Dept Manage',
        deptCode: 'Dept Code',
        deptName: 'Dept Name',
        upperDept: 'Parent Dept',
        org: 'Company',
        enable: 'enable',
        unable: 'unable',
        isVirtual: 'isVirtual',
        deptStatus: 'Status',
        hasChild:'Delete subdivision nodes first',
        isUsing:'here are users under this department and they cannot be deleted for the time being.',
        placeholder: {
            org: 'Please select company',
            deptCode: 'Please input Dept Code',
            deptName: 'Please input Dept Name',
            upperDept: 'Please select upper Dept',
            isVirtual: 'Please select isVirtual',
            deptStatus: 'Please select Status'
        },
        selectDept: 'Please select Dept',
        selectCompany: 'Please select company',
        displayMode: 'Display mode',
        repeatDeptCode: 'Departmental codes already exist for the same company',
        list: 'List',
        level: 'Level',
        checkSuperDept: 'Superior departments should not be the current departments'
    },
    resourcePage:{
        isExternalLink:'External links',
        isShow:'Display in menu',
        isDtauthControl:'Data Rights Control',
        isClickRefresh:'Whether to click refresh',
        resourceManage:'Resource Manage',
        choose:'Choose',
        resourceCode:'Res Code',
        resourceName:'Res Name',
        resourceUpper:'Parent Res',
        resourceIcon:'Icon',
        resourceType:'Res Type',
        resourceOrder:'Sort',
        resourceUrl:'Res URL',
        resourceDes:'Res Des',
        resourceFlag:'Author Code',
        resourceStatus:'Res Status',
        enableStatus:'Enable',
        unableStatus:'Unable',
        editMessage:'Please choose your edit node firstly',
        deleteMessage:'Please choose you delete node firstly',
        delConfirmMes:'The action will delete the resource permanently, go on or not?',
        delTip:'Tips',
        delSuccess:'Deleted Successfully',
        cancelDelete:'Canceled',
        noDelMessage:'The node has child nodes，can\'t delete directly',
        saveMessage:'Saved Successfully',
        type:'Type',
        catalog:'Directory',
        menu:'Menu',
        btn:'Button',
        placeholder: {
            resourceName:'please input resource name',
            resourceCode: 'please input resource code',
            resourceUpper:'please input upper menu',
            resourceUrl:'please input resource url',
            resourceOrder: 'please input resource order',
            resourceIcon: 'please input resource icon',
            notEmpty:'Unique and not empty, such as sys_menuUser',
            notEmptyEx:'Unique and not empty, such as sys',
            notEmptyExTwo:'Unique and not empty, such as sys_user_add',
            notEmptyExThree:'such as sys:user:info'
        }

    },
    workbenchToDoPage:{
        title:'Todo Task',
        moreAction:'More',
        sign:'Sign For',
        export:'Excel Export',
        selfCol:'Self-Defined Column',
        advancedQuery:'Advanced Query',
        businessKey:'Wo Code',
        businessInfo:'Subject',
        priority:'Priority',
        priorityOptions:{
            general:'General',
            urgency:'Urgency',
            extraUrgent:'Eextra Urgent'
        },
        startUser:'Initiator',
        createTime:'Creation Time',
        startTime:'Start Time',
        endTime:'End Time',
        processTrace:'Process Trace',
        tableList:'Todo',
        currentName:'Cur Node',
        status:'Pending',
        oneWeek:'In the latest week',
        oneMonth:'Last month',
        threeMonth:'Last 3 months',
        signNoneMsg:'Data to sign for is not selected',
        signHaveMsg:'To-do list signed, no need to sign again',
        signSuccess:'Sign for successful'
    },
    workbenchDonePage:{
        title:'Done Task',
        signTime:'Signed Time',
        taskEndTime:'End Time'
    },
    workbenchToReadPage:{
        title:'Reading Task',
        orderType:'Document Type',
        circulator:'Circulator'
    },
    workbenchReadedPage:{
        title:'My Have Read',
        sDate:'Accept Circulated Time'
    },
    workbenchFlowTestPage:{
        title:'Process Test Work Order',
        feeType:'Fee Type',
        orderCode:'Wo Code',
        orderType:'Order Type',
        feeAmount:'Fee Amount',
        status:'Status',
        remark:'remark',
        feeOptions:{
            transportation:'transportation',
            accommodation:'accommodation',
            other:'other'
        },
        inProcess:'Selected data cannot be manipulated inProcess',
        notinProcess:'Selected data cannot be manipulated not inProcess',
        entity:{
            title:'Travel Expense Apply',
            autogeneration:'Autogeneration',
            applyDate:'Apply Date',
            people:'Applicant',
            department:'Department',
        },
        editOrder:'Edit Order',
        viewOrder:'View Order'
    },
    workbenchBatchTurn:{
        title:'Batch transfer to others',
        dpeople:'Transactors',
        zpeople:'Transferred person',
        chooseTaskTip:'Please select the tasks to be transferred'
    },
    workbenchSharedDocPage:{
        title:'Shared Document',
        docSearch:'Document search',
        dirAdd:'Add Dir',
        dirName:'Dir Name',
        dirCode:'Dir Code',
        dirDec:'Dir Desc',
        msg1:'Directory code repeated, please modify',
        msg2:'Child nodes under this node cannot be directly deleted',
        msg:'Shared document management',
        dir:'Document directory',
        myDoc:'My document',
        comDoc:'Company document',
        three:'3',
        inputDirName:'Please enter directory name'
    },
    accessory:{
        title:'add attachment ',
        type:'Type',
        description:'Attachment Desc',
        name:'Attachment name',
        upload:'Upload',
        download:'Download',
        uploadSuccess:'Upload successful',
        people: 'Uploader',
        time:'Upload Time',
        templateSize:'Upload templateSize cannot exceed 30MB!',
        uploadFirst:'Please upload attachments first',
        downloading:'downloading...',
        downloadCompletes:'Download completion',
        msg1:'Currently limited to select 3 files, selected this time',
        msg2:'file, total selected',
        msg3:'files'
    },
    rolePage:{
        roleExtensionInfo:'Role Extension Information',
        ownCompany:'The role of company ownership',
        permissionDist:'Allocation of Personnel Rights',
        roleSearch:'Role Search',
        roleManage:'Role Manage',
        fnPermission:'Func Permission',
        dataPermission:'Data Permission',
        chooseEnterprise:'Choose Com.',
        roleCode:'Role Code',
        roleName:'Role Name',
        roleStatus:'Role Status',
        roleType:'Role Type',
        roleOrg:'Role Org',
        roleCompany:'Role Company',
        roleDes:'Role Des',
        creatorName: 'Creator Name',
        repeatRoleNameMes:'Role name is existed！please input role name again！',
        repeatRoleCodeMes:'Role code is existed！please input role code again！！',
        placeholder:{
            roleCode:'Please input role code',
            roleName:'Please input role name',
            roleType:'Please input role type',
            chooseEnterprise: 'Please choose company',
            roleDes:'Please input role Des',
            roleStatus:'Please choose status'
        }
    },
    dictPage:{
        dictManage:'Dict Manage',
        dictItemManage:'Dict Item Manage',
        dictCode:'Dict Code',
        dictItemCode:'Dict Item Code',
        dictName:'Dict Name',
        dictItemName:'Dict Item Name',
        dictDes:'Dict Des',
        dictItemDes:'Dict Item Des',
        manageDict:'Manage Dict',
        addNew:'Add Line',
        delLine:'Delete Line',
        placeholder:{
            dictCode:'Please input dict code',
            dictName: 'Please input dict name',
            dictDes: 'Please input dict des'
        },
        dictMes:{
            allDictItem:'Please input the whole dict items',
            noRepeatCode:'Dict item code can\'t repeat',
            existedCode:'Dict code existed，please input it again'
        }
    },
    myApprovalBtn:{
        approval:'Approval',
        approveAct:'Approval Act',
        approvalAct:'Approval Act',
        cancelApproval:'Cancel Approval',
        return:'Return',
        returnAct:'Return Act',
        consult:'Consult',
        confirmConsult:'Confirm Consult',
        consultPeople:'Consult People',
        consultAct:'Consult Act',
        choseConsultPeople:'Please chose Consult People',
        forward:'Forward',
        forwardSuccess:'Forward success',
        confirmForward:'Confirm Forward',
        choseForwardPeople:'Please chose Forward People',
        retrieve:'Retrieve',
        confirmRetrieve:'Confirm Retrieve?',
        retrieveSuccess:'Retrieve success',
        nextNode:'Next Node',
        dealingPeople:'Dealing People',
        processHandle:'Process Handle',
        autoNode:'Auto Node',
        choseCirculator:'Please chose Circulator',
        countersignedIntention:'Countersigned Intention',
        agree:'Agree',
        disAgree:'DisAgree',
        approvalOpinion:'Approval Opinion',
        saveOpioion:'Save Opioion',
        commonOptions:'Common Options',
        flowTo:'Flow To',
        choseFlowTo:'Please choose the direction of flow',
        approvalOpinionsEmpty:'Failure to fill in approval opinions',
        endProcess:'End Process',
        confirmEndProcess:'Confirm the end process?',
        revocationProcess:'Revocation process',
        confirmRevocationProcess:'Confirmation revocation process？',
        successfulCancellation:'Successful cancellation',
        beforeAdd: 'Before signing',
        afterAdd: 'After signing',
        choseAddPeople: 'Please Chose Add People'
    },
    trackList:{
        dealingPeople:'Dealing People',
        node:'Node',
        approvalAct:'Approval Act',
        approvalState:'Approval State',
        approvalTime:'Approval Time',
        approvalContent:'Approval Content'
    },
    postManage:{
        postManagement:'Post management',
        postCode:'Post Code',
        postName:'Post Name',
        orderNum:'Order Number',
        status:'Status',
        postType:'Post Type',
        enable:'Enable',
        prohibit:'Prohibit',
        jobExpansionInfo:'Job Expansion Information'

    },
    rolePermission: {
        fnPermission: 'Fun Auth',
        dataPermission: 'Data Permi',
        attributionCompany: 'Attribution Company'
    },
    rolePerson:{
        rolePerson: 'Assign people to roles',
        assignPerson: 'Assign people',
        choseUser:'Chose User',
        userName:'Login Name',
        cname:'name',
        orgs:'Department',
        status: 'Status',
        mobile:'Mobile',
        position:'Role',
        roleName:'Role Name',
        orgNames:'Organization',
        enable:'Enable',
        prohibit:'Disable',
        selectRoles:'Please select roles',
        treeChart:'Tree organization chart',
        selectCompany: 'Please choose the company to belong to',
        attributionCompany: 'Attribution Company'
    },
    userRemindTepMage:{
        userRemTemplate:'User reminder template management',
        chineseName:'Template name',
        templateType:'Template type',
        englishName:'English Name of Template',
        templateManagement:'Template management',
        editBox:'Edit box',
        replace:'Replacement Character List',
        ekey:'Names to be replaced',
        evalue:'Description'
    },
    document:{
        infoManagement:'Information management',
        documentTitle:'Title',
        documentType:'Type',
        documentEnable:'Is it effective',
        documentDesc:'memo',
        choseOneMsg:'Please select a data',
        canNotDel:'Selected data cannot be deleted in the process'
    },
    cfields:{
        extendedFieldManage:'Extended Field Management',
        cfObjCode:'Extended object',
        cfCfieldType:'Field type',
        cfCfieldLabel:'Field display name',
        cfCfieldColumn:'Database field',
        sort:'Sort',
        cfDtype:'Data dictionary'
    },
    images:{
        imageManagement:'Picture management',
        name:'Title',
        type:'Type',
        statusText:'Whether effective',
        remark:'Remarks',
        picture:'Picture',
        tips:'Upload template size can not exceed 64KB!',
        tipsEx:'Upload files not exceeding 200K',
        warningMsg:{
            one:'Current restrictions on the selection of three documents, the choice of this time',
            two:'files, selected altogether',
            three:'files'
        }
    },
    log:{
        operateType:'Operation type',
        createTime:'Operation time',
        startTime:'Start time',
        endTime:'End time',
        title:'Default query operation records for the last 7 days',
        requestIp:'Operation IP',
        description:'Operation description',
        actionUrl:'Request URL',
        actionMethod:'Request method',
        lastWeek:'Last week',
        lastMonth:'Last month',
        lastThreeMonths:'The last three months',
        loginName:'Login Name',
        loginCname:'Landing nam',
        visitTime:'Visit time',
        lgoutDate:'logout time',
        ipAddress:'Login IP',
        clientos:'Client System',
        browserName:'Client Browser',
        accessLog:'User Access Log',
        operationsLog:'User Operations Log',
        requestParameters:'Request parameters',
        responseParameter:'Response parameters'
    },
    schedule:{
        timingManage:'Timing Task Management',
        timingInfo:'Timing Task Information',
        timingLog:'Timing Task Log',
        immediate:'Immediate execution',
        logList:'Log list',
        beanName:'bean Name',
        methodName:'Method Name',
        params:'Params',
        cronExpression:'cron Expression',
        remark:'Memo',
        sureSuspend:'Sure to suspend operation?',
        sureRecovery:'Determine recovery operations?',
        immediateAction:'Determine immediate action?',
        successful:'Successful implementation',
        fail:'Execution failure',
        jobId:'Task ID',
        times:'Time-consuming (milliseconds)',
        createTime:'Execution Time'
    },
    model:{
        modelManagement:'Model management',
        deploy:'Deploy',
        configuration:'Configuration',
        export:'Export',
        company:'company',
        key:'Model Key',
        name:'Model Name',
        version:'Version',
        deploymentTime:'Deployment Time',
        createTime:'Create Time',
        lastUpdateTime:'Last Update Time',
        sureDeploy:'To determine the deployment?',
        exportSuccess:'Export success！',
        pleaseChose:'Please Chose',
        addModel:'Add model',
        description:'Model description',
        tenantName: 'Company'
    },
    process:{
        processManagement:'Process Management',
        key:'Process Key',
        name:'Process Name',
        version:'Version',
        latestVersion: 'Latest version NO.',
        processImport:'Process import',
        change:'Conversion to model',
        activation:'Activation',
        modelName:'Model Name',
        deploymentTime:'Deployment Time',
        lastDeploymentTime:'Last Deployment Time',
        description:'Description',
        sureChange:'Determine whether to convert to a model?',
        sureDel:'Confirm removal',
        checkVersion:'View Versions',
        processVersion:'Process Versions',
        checkInstance:'View Instances',
        processInstance:'Process Instances'
    },
    instance:{
        instanceManagement:'Instance Management',
        key:'Instance Key',
        procDefName:'Instance Name',
        name:'Business information',
        moduleName:'Module name',
        applyPerson:'Initiator',
        curTaskName:'Current process node',
        curTaskCreateTime:'Current task creation time',
        curTaskAssignee:'Current Handler',
        sureDel:'Determine whether to force deletion of process instances?'
    },
    entrustProcess:{
        processDelegation:'Process delegation',
        add:'Add delegate',
        woName:'Type of work order',
        consignerName:'Client',
        mandataryName:'Principal',
        beginDateText:'Start date',
        endDateText:'End date',
        activeText:'Operation mark',
        title:'Please select the client',
        activation:'Activation',
        close:'Close',
        startTime:'Start Time',
        endTime:'End Time'
    },
    mapping:{
        title:'Worksheet and process config',
        add:'Add',
        woType:'Document type',
        procName:'Process name',
        procKey:'Process key',
        procVersion:'Version',
        JobAllocation:'Job Allocation',
        url:'Jump path',
        msg:'Document type already exists! Please re-select the document type'
    },
    custRule:{
        processRules:'Process rules',
        orderType:'Order Type',
        processName:'Process Name',
        processKey:'Process key',
        processVersion:'Version',
        nodeCode:'Node Code',
        nodeName:'Node Name',
        remark:'Rule description',
        rule:'Rule',
        msg:'No illegal fields such as update, insert, etc. in rules'

    },
    changePassword:{
        changePassword:'Change Password',
        pwdCur:'Old password',
        pwdNew:'New password',
        pwdConfirm:'Confirm password',
        formatError:'The new password format is incorrect',
        samePwd:'The new password is the same as the original password. Please re-enter or cancel it',
        success:'The password was changed successfully. Please login again',
        fail:'Failed to change password',
        difPwd:'Confirm that the password is inconsistent with the new password. Please re-enter it',
        curPwdError:'The original password is incorrect. Please re-enter it'
    },
    message:{
        MsgNotification:'Message notification',
        readed:'Mark as read',
        allReaded:'All marked as read',
        subject:'Theme',
        content:'Content',
        emailFromName:'Sender',
        createTime:'Dispatch time'
    },
    branchManager:{
        title:'Branch Manager',
        userName:'User account',
        cname:'User name',
        deptName:'company',
        add:'Branch Manager - Added',
        choseWaring:'Please select the branch manager',
        checked:'Selected personnel',
        companyList:'Company List',

    },
    ...enLocale,
    ...business_en_Us
}
export default en_US;
